### PR TITLE
Added the PDF version.

### PR DESCRIPTION
**Pull request by mahdi**
I added the PDF version of markdown which can be easily shared as a single file readable on all devices.

### CODE REVIEW

**Comment by garethj-msft** [comment]
Hi Mahdi.  As an evolving document, we can't really take a point in time PDF snapshot.  What toolset did you use to create this - maybe we can spin it up as a webhook on the repo so it stays up to date?

**Comment by mahdi** [comment]
Hi @garethj-msft, I used an online convertor but it looks like this tool can do what you mentioned: [https://cloudconvert.com/api/convert/md-to-pdf](url)

**Comment by RobDolinMS** [comment]
Towards the goal [Madhi stated](https://github.com/Microsoft/api-guidelines/pull/75#issue-190974094) of having something "easily shared as a single file readable on all devices" 

Since the GitHub repo is public and the guidelines.md file is rendered by GitHub as HTML in this view: https://github.com/Microsoft/api-guidelines/blob/master/Guidelines.md ... I believe we have a single file readable on all devices.  

Given the above and [Gareth's concern](https://github.com/Microsoft/api-guidelines/pull/75#issuecomment-262438214) about not wanting a snapshot that could get out-of-date, I'm closing this PR to add the PDF.

**Comment by dodekeract** [comment]
Weird. I can't read a PDF in my terminal. I thought it's more compatible than markdown!

**Pull request closed without merging**
