### PR TITLE
Remove use of "REST" from section titles

### PR DESCRIPTION
**Pull request by RobDolinMS**
Removes the possibly extraneous use of "REST" for two section titles
Includes edits in table of contents

### CODE REVIEW

**Comment by cleemullins** [comment]
LGTM. These are certainly removable...

**Comment by sharwell** [comment]
:+1:

**Comment by dodekeract** [comment]
@sharwell, you can now use the "add your reaction" button to add a :+1: without spamming everybody's inbox.

**Comment by sharwell** [comment]
@dodekeract That doesn't mark me as a participant in the topic.

image

**Comment by RobDolinMS** [comment]
With me as the author and a LGTM from @cleemullins, I'm merging this one.

**Pull request merged**
