### PR TITLE
Replace usages of "object"

### PR DESCRIPTION
**Pull request by glennblock**
Replace usages of "object' with "resource" when it pertains to the HTTP spec / HTTP methods

### CODE REVIEW

**Comment by garethj-msft** [comment]
LGTM

**Comment by glennblock** [comment]
Thanks @garethj-msft!

**Comment by johngossman** [comment]
LGTM

**Comment by glennblock** [comment]
Sweet, thanks!

**Comment by glennblock** [comment]
Thank you all!

**Pull request merged**
