### PR TITLE
Document all LRO values in Azure Guidelines

### PR DESCRIPTION
**Pull request by heaths**

### CODE REVIEW

**Comment by heaths** [comment]
@JeffreyRichter both the Azure MD files mentioned both LRO patterns for resource-based and general POST

**Review by JeffreyRichter — APPROVED** [review]

**Comment by heaths** [comment]
@JeffreyRichter @mikekistler I don't have permissions to merge this. Just wanted to point that out since you might've expected it, given we typically do that with SDK repos.

**Comment by JeffreyRichter** [comment]
@markweitzel can merge this

**Review by mikekistler — APPROVED** [review]
Looks good! 👍

**Pull request merged**
