### PR TITLE
Use consistent casing throughout the guidelines

### LINKED ISSUE #8: Many parts of the guidelines are in all caps
I'm aware of [RFC2119](https://www.ietf.org/rfc/rfc2119.txt) which recommends to capitalize certain key words but was wondering if there's also a reason to all capitalize for example headings and the table of contents?

If there is no greater reason, I would vote to either Title case or Start Case the guidelines to increase readability and make them more friendly to the eyes of the reader.

### PR DESCRIPTION
**Pull request by BasThomas**
Fixes #8

### CODE REVIEW

**Comment by cleemullins** [comment]
Hi BasThomas. Thanks for doing this! I really like it, and once I can get a second set of eyes here on it to verify, will merge. CAPITAL LETTERS == ICK!

**Comment by lumaxis** [comment]
Although I'm not a maintainer of this project, I have it a quick look and it looks good to me too 👍 
Especially like that the headings use sentence-style capitalization as recommended by the [Microsoft Manual of Style](https://www.microsoftpressstore.com/store/microsoft-manual-of-style-9780735648715).

**Comment by RobDolinMS** [comment]
THANK YOU @BasThomas for putting this large PR together.  
LGTM 👍

**Comment by RobDolinMS** [comment]
Merging per LGTM's from @cleemullins and me

**Comment by lumaxis** [comment]
@RobDolinMS I see what you did there 😄 💥
 
Great to have this in, huge improvement imo! Thanks to @BasThomas for getting your PR in before I could properly start work on this 🙂

**Comment by BasThomas** [comment]
You're welcome! 😊

**Pull request merged**
