### PR TITLE
Replace the term verb with method #7

### PR DESCRIPTION
**Pull request by darrelmiller**

### CODE REVIEW

**Comment by cleemullins** [comment]
I was all ready to push back on this, with "I've read these RFC's hundreds of times, and it's VERB not Method". Then, just now, I went and re-read the relevant RFC's yet one more time. 

Damn.

All these years I've been reading the word "Method" and thinking it said "Verb". 

Thanks for this. Good to get it right, especially when "Right" is so clearly "method" and NOT "verb". 

LGTM. Can I get a second?

**Comment by darrelmiller** [comment]
:-) I've been there.

**Comment by sharwell** [comment]
:+1:

**Comment by glennblock** [comment]
@cleemullins it is super common that people use VERB though it is never mentioned in the RFC.

**Comment by RobDolinMS** [comment]
Thanks for this @darrelmiller.  The PR looks like a solid find/replace of verb -> method.  
Per my own sometimes referencing of HTTP methods as HTTP verbs, and @cleemullins's and @glennblock's comments above; I hesitate on a LGTM.  
Would it make sense to also include a sentence in the opening paragraph of section 7.4 mentioning that these are sometimes known as "verbs"?

**Comment by johngossman** [comment]
I agree with @RobDolinMS on a quick sentence about methods often being called verbs.

**Comment by glennblock** [comment]
That seems reasonable to me.

**Comment by cleemullins** [comment]
Ok. @darrelmiller If you could add in the quick sentence that Rob & John are referring to, I can merge once that's done.

**Comment by cleemullins** [comment]
@darrelmiller I'm good to merge this. @garethj-msft Your turn!

**Comment by garethj-msft** [comment]
I would like to get the sentence per @glennblock @RobDolinMS & @johngossman if you don't mind, then I'll go ahead and merge Darrel.

**Comment by darrelmiller** [comment]
@garethj-msft I have merged master and added the line about the use of HTTP verb.  So, if that sentence works for you, this should be good to go.

**Comment by garethj-msft** [comment]
LGTM

**Pull request merged**
